### PR TITLE
Update utilities.js

### PR DESCRIPTION
**Pull request by hansemannn**
Add filters for platform-only API's. Required for https://github.com/appcelerator/titanium_mobile/pull/9541

### CODE REVIEW

**Comment by hansemannn** [comment]
Merging to be unblocked.

**Comment by sgtcoolguy** [comment]
@hansemannn This should be reverted. There are already `ios`, `android`, `windows` filters. They only run and report the test on the specific platform *and do not even skip the test on others*. I'm trying to make a skipped test mean there's a bug or API parity issue, and if a test is specific to one platform it shouldn't even be reported at all for the others.

**Comment by hansemannn** [comment]
I reverted the change, but master may fail now. Can you give an example of the iOS-only usage?

**Comment by sgtcoolguy** [comment]
```javascript
it.ios('test name', function () {
  // iOS-specific test
});
```

**Pull request merged**
